small change in cd_staging 6

diff --git a/.github/workflows/cd_staging.yml b/.github/workflows/cd_staging.yml
--- a/.github/workflows/cd_staging.yml
+++ b/.github/workflows/cd_staging.yml
@@ -16,8 +16,17 @@ jobs:
        - name: SSH and deploy
          run: | 
            ssh -o StrictHostKeyChecking=no -i ssh_key ubuntu@13.60.166.224 << 'EOF'
-            cd CI_CD_Certmanagement/ && git pull
-            pnpm install
-            pnpm run build
-            pm2 restart all
-           EOF
+           set -e  # exit on first error
+              echo "✅ Connected to server"
+              cd CI_CD_Certmanagement/ || { echo "❌ Folder not found"; exit 1; }
+              echo "✅ Pulled into repo"
+              git pull
+              echo "✅ Installing dependencies..."
+              which pnpm || { echo "❌ pnpm not found"; exit 127; }
+              pnpm install
+              echo "✅ Building..."
+              pnpm run build
+              echo "✅ Restarting server..."
+              which pm2 || { echo "❌ pm2 not found"; exit 127; }
+              pm2 restart all
+            EOF
